---
- name: reload systemd and restart gcode-proxy
  systemd:
    name: gcode-proxy
    state: restarted
    daemon_reload: true

- name: restart gcode-proxy
  systemd:
    name: gcode-proxy
    state: restarted