hass_server_secret: ENC[AES256_GCM,data:h29q2QxP08ETX66Sb59Dy3/Uxy6fLA==,iv:HbYhMz/Gc18H7sXRPRWMuE2w2KY07h1uCUtiJD0T/vI=,tag:lTJKBTofcgcDNKB5EED2aQ==,type:str]
hass_token_secret: ENC[AES256_GCM,data:AAxO1Kis10M9XT4Q6gNUOIXf8ORcrP/c2ITQn4Bkng7uD4neWwm068L3Stfyi/omSeMf1GgkV/r16g90Kn0ZqGxY8kPHr3Jxf6bUsALmJTY/QmH1aPqWADrzBXhwHOZRB4eM1fNU1ypBMFniLSg39kxZQzWqYxxkmlzO33netUkeNF6Kq7QefzyxC6Ve+M0+F9QDApXMr9y4OiROCFnMfZpws3qfXSBEpHySwI1d86yP5AVDWRpQ,iv:KiTgSsjauoQcC2eIvMGtOCNRBrR1QXs+5cJD/IFZCkM=,tag:lJcaNAn0GBw9ydeKU2t3uA==,type:str]
sops:
    lastmodified: "2026-01-22T20:45:39Z"
    mac: ENC[AES256_GCM,data:GzNp7P0A4CjACKOB2MGUWvLcNP53xtfIQLhPJYwTrh/kalR3rZncGaswQ//e30e+jSL1KfrIvTs6ORYfMTA01QB0vEpJ4AYQDp40/QU2YS1BWlsQ0zH9e40VJJCNMy7pl4jng+mdJ5kd1fp++jdvLJHoFBVE5cWpA54D7bqZQBs=,iv:ZtpnGZTbVS4J9VJxAlFiYIrBxHdlgtMCXH+4lIHLQrg=,tag:bCJhcvW4DFdbRme+hnQ7Dw==,type:str]
    pgp:
        - created_at: "2026-01-22T20:45:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//WaZYkueHWxMSxOhsH879fMI9Yl/vinV07OcM09xmZlDS
            csH9EeTwYptvlBYkqp94JH+6Kggfyfkty8euUPxMIOZ1WvMlMmo144MC5HwCzzYx
            CyMlqj8fO5GXvJcWeCvdRIZtOSrWOiQ31wRETQtziKMqUnVTCScAV+eXA3g/veoA
            DxsoRciaVflmOOj0d9/gg4b6JtpT4P1UubQ2yLIiWm0D3PH0NIf3euAMp5giiitx
            iPn8+GB+XGSJT1IpN2lVPMf/waPklX2FT2JvAkcMVys2wUiKzUCOlG7KP5vctohw
            Oh01wDCxhk5fBSBB6sDTMxuY24e/lGx0MCJ1oc4yMaQLNDvPcAvBHV2RIWu/evdh
            Wj71/v03+PsY4yJ42STn/yoxuyLxLf0zYXucSexkRsZpPB5m8lthrHmiSJIWhheB
            E2SJUCOvMk7up+RdBEGPGkDUKsv9q6zmLBrPemEK5GYPWLQen3nms6lM7wRefZAm
            isJuB1kb2Si89D//6hiN/vPE2vxMP4cYCVXdar9mMhKolI+v/YPtUwdz3Hf1rqQx
            3oSPG6L5jv5EqYyOEegvLtJC9OnfJkjvGBjyFOAIyIESXtW7Xv12CwwJmOHtPXCB
            Mudgnrlk3p9Ih8dj2Yk4Uz5jlwfGImeJwYpJssWcDLkCIQXcwY7IR0sc7MzXGPrS
            XAHaOeTZcS5nSzA3XSpdZbMkrNa7XGWItNuG67J+/9lUc+w7UQ3NPq53FO2Ay/Lc
            KzezhnfIwRrfLS57fJm85SVeeuetXOhLJ58O+PfzIZiTSg/8YzVLmxVKlmcj
            =Ajh6
            -----END PGP MESSAGE-----
          fp: A2AF5A4B747411B2D6B9331CFA018F24752F2F6E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
